version: '2'
services:
  postgresql:
    image: docker.bintray.io/postgres:9.6.11
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=password
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory-node1:
    image: docker.bintray.io/jfrog/artifactory-pro:6.7.0
    container_name: artifactory-node1
    ports:
     - 8081:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    volumes:
     - /data/artifactory/node1:/var/opt/jfrog/artifactory
    environment:
     - ARTIFACTORY_MASTER_KEY=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
     - HA_IS_PRIMARY=true
     - HA_MEMBERSHIP_PORT=10017
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=password
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory-node2:
    image: docker.bintray.io/jfrog/artifactory-pro:6.7.0
    container_name: artifactory-node2
    ports:
     - 8082:8081
    depends_on:
     - postgresql
     - artifactory-node1
    links:
     - postgresql
    # Must pass this to non primary so it can wait for primary to be up
     - artifactory-node1
    volumes:
     - /data/artifactory/node2:/var/opt/jfrog/artifactory
    environment:
     - ARTIFACTORY_MASTER_KEY=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
     - HA_IS_PRIMARY=false
     - HA_MEMBERSHIP_PORT=10017
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=password
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:6.7.0
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory-node1
     - artifactory-node2
    links:
     - artifactory-node1
     - artifactory-node2
    volumes:
     - /data/nginx:/var/opt/jfrog/nginx
    environment:
     - ART_BASE_URL=http://artifactory-node1:8081/artifactory
     - SSL=true
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
