# Default values for artifactory.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# Common
replicaCount: 1
imagePullPolicy: IfNotPresent
initContainerImage: "busybox:1.26.2"
db_env:
  db_type: postgresql
  db_name: artifactory
  db_user: artifactory
  db_pass: artYifactory1973

# DB
db_name: postgresql
db_image:
  repository: docker.bintray.io/postgres
  version: 9.5.2
db_service:
  name: postgresql
  type: ClusterIP
  externalPort: 5432
  internalPort: 5432
db_persistence:
  mountPath: "/var/lib/postgresql/data"
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

# Artifactory
art_name: artifactory
art_replicaCount: 1
art_image:
  repository: docker.bintray.io/jfrog/artifactory-oss
  version: 5.3.2
art_service:
  name: artifactory
  type: LoadBalancer
  internalPortHttp: 8081
  externalPortHttp: 80
art_persistence:
  mountPath: "/var/opt/jfrog/artifactory"
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
