apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifactory-ha-node1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory-ha
        role: artifactory-primary
        group: artifactory-k8s-demo
    spec:
      containers:
      - name: artifactory-ha-node1
        # Set your actual artifactory-pro image
        image: <your-docker-reg>/jfrog/artifactory-pro-mysql:5.7.2
        env:
        - name: DB_TYPE
          value: mysql
        - name: DB_USER
          value: artifactory
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: mysql-k8s-service
        - name: HA_IS_PRIMARY
          value: "true"
        - name: HA_NODE_ID
          value: ha-node1
        - name: HA_MEMBERSHIP_PORT
          value: "10117"
        - name: ARTIFACTORY_MASTER_KEY
          value: "fc9dfbbfb055f18c765ed19e63ad41a9e1fda67bdb6a24ebfb2aeb6aa6349549"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: artifactory-node1-volume
          mountPath: "/var/opt/jfrog/artifactory"
        - name: binarystore-xml
          mountPath: "/var/opt/jfrog/artifactory/etc/binarystore.xml"
          subPath: binarystore.xml
        readinessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 180
          periodSeconds: 10
      volumes:
      - name: artifactory-node1-volume
        persistentVolumeClaim:
          claimName: artifactory-node1-claim
      - name: binarystore-xml
        configMap:
          name: artifactory-binarystore
      imagePullSecrets:
      - name: docker-reg-secret
---
# This service it to allow all new member nodes to check that primary is up
apiVersion: v1
kind: Service
metadata:
  name: artifactory-node1
  labels:
    app: artifactory-ha
    group: artifactory-k8s-demo
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
  selector:
    role: artifactory-primary
