apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-k8s-deployment
        group: artifactory-k8s-demo
    spec:
      containers:
      - name: nginx-k8s
        image: docker.bintray.io/jfrog/nginx-artifactory-pro:5.3.1
        env:
        - name: ART_BASE_URL
          value: "http://artifactory-pro:8081/artifactory"
        - name: SSL
          value: "true"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: nginx-volume
        - mountPath: "/var/opt/jfrog/nginx/conf.d"
          name: configmap-volume
        - mountPath: "/var/opt/jfrog/nginx/ssl"
          name: ssl-secret-volume
      volumes:
      - name: configmap-volume
        configMap:
          name: nginx-artifactory-conf
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: nginx-claim
      - name: ssl-secret-volume
        secret:
          secretName: art-tls
